<?php

namespace Database\Seeders;

use App\Models\FormFieldValidation;
use Illuminate\Database\Seeder;

class FormFieldValidationSeeder extends Seeder
{
    public function run(): void
    {
        $fields = [
            // ==========================================
            // 1. PURCHASE MODULES
            // ==========================================
            // Purchase Invoices
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'invoice_date',
                'field_label' => 'Invoice Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date is not allowed for Invoice Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select a valid supplier.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Branch selection is required.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'grn_number',
                'field_label' => 'GRN Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => true,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'GRN Number already exists. Please use a unique GRN Number.',
                'sort_order' => 4,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'grn_date',
                'field_label' => 'GRN Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for GRN Date.',
                'sort_order' => 5,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_no',
                'field_label' => 'Supplier Inv No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Supplier Invoice Number is already recorded for this supplier.',
                'sort_order' => 6,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_date',
                'field_label' => 'Supplier Inv Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for Supplier Inv Date.',
                'sort_order' => 7,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_amount',
                'field_label' => 'Supplier Inv Amount',
                'field_type' => 'number',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Inv Amount (Supplier) and Final Amount must match.',
                'sort_order' => 8,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'purchase_type',
                'field_label' => 'Purchase Type (Local/Interstate)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please choose Local or Interstate purchase type.',
                'sort_order' => 9,
            ],

            // Purchase Orders
            [
                'module_key' => 'purchase_orders',
                'field_name' => 'po_date',
                'field_label' => 'PO Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for PO Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_orders',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'custom_error_message' => 'Supplier selection is required.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_orders',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'custom_error_message' => 'Branch selection is required.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_orders',
                'field_name' => 'purchase_type',
                'field_label' => 'Purchase Type',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'custom_error_message' => 'Purchase type is required.',
                'sort_order' => 4,
            ],
            [
                'module_key' => 'purchase_orders',
                'field_name' => 'c_form',
                'field_label' => 'C-Form',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],

            // Purchase Receipt Notes (GIN)
            [
                'module_key' => 'purchase_receipt_notes',
                'field_name' => 'receipt_date',
                'field_label' => 'Receipt Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for Receipt Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_receipt_notes',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_receipt_notes',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_receipt_notes',
                'field_name' => 'supplier_challan_no',
                'field_label' => 'Supplier Challan No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],
            [
                'module_key' => 'purchase_receipt_notes',
                'field_name' => 'vehicle_no',
                'field_label' => 'Vehicle No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],

            // Purchase Indents
            [
                'module_key' => 'purchase_indents',
                'field_name' => 'indent_date',
                'field_label' => 'Indent Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_indents',
                'field_name' => 'required_by_date',
                'field_label' => 'Required By Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_indents',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_indents',
                'field_name' => 'department',
                'field_label' => 'Department',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],
            [
                'module_key' => 'purchase_indents',
                'field_name' => 'priority',
                'field_label' => 'Priority (Low/Medium/High/Urgent)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],

            // Purchase Returns
            [
                'module_key' => 'purchase_returns',
                'field_name' => 'return_date',
                'field_label' => 'Return Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_returns',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_returns',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_returns',
                'field_name' => 'supplier_debit_note_no',
                'field_label' => 'Supplier Debit Note No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],

            // ==========================================
            // 2. SALES MODULES
            // ==========================================
            // Sales Bills
            [
                'module_key' => 'sales_bills',
                'field_name' => 'bill_number',
                'field_label' => 'Bill Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => true,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Bill Number already exists.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'bill_date',
                'field_label' => 'Bill Date & Time',
                'field_type' => 'datetime',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date and time is not allowed for Bill Date.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select a customer for this bill.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Branch selection is required.',
                'sort_order' => 4,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'invoice_type',
                'field_label' => 'Invoice Type',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select an invoice type.',
                'sort_order' => 5,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'delivery_type',
                'field_label' => 'Delivery Type',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Delivery type is required.',
                'sort_order' => 6,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'sales_type',
                'field_label' => 'Sales Type (Local/Interstate)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Sales type is required.',
                'sort_order' => 7,
            ],

            // Sales Returns
            [
                'module_key' => 'sales_returns',
                'field_name' => 'return_date',
                'field_label' => 'Return Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_returns',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_returns',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_returns',
                'field_name' => 'sales_bill_id',
                'field_label' => 'Original Sales Bill',
                'field_type' => 'select',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],

            // Sales Quotations
            [
                'module_key' => 'sales_quotations',
                'field_name' => 'quotation_date',
                'field_label' => 'Quotation Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_quotations',
                'field_name' => 'valid_until',
                'field_label' => 'Valid Until Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_quotations',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_quotations',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],

            // Sales Orders
            [
                'module_key' => 'sales_orders',
                'field_name' => 'order_date',
                'field_label' => 'Order Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_orders',
                'field_name' => 'expected_delivery_date',
                'field_label' => 'Expected Delivery Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_orders',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_orders',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],

            // Sales Delivery Notes
            [
                'module_key' => 'sales_delivery_notes',
                'field_name' => 'delivery_date',
                'field_label' => 'Delivery Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_delivery_notes',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_delivery_notes',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_delivery_notes',
                'field_name' => 'vehicle_no',
                'field_label' => 'Vehicle No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],
            [
                'module_key' => 'sales_delivery_notes',
                'field_name' => 'driver_name',
                'field_label' => 'Driver Name',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],

            // ==========================================
            // 3. INVENTORY MODULES
            // ==========================================
            // Stock Transfers
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'transfer_date',
                'field_label' => 'Transfer Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date is not allowed for Transfer Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'from_branch_id',
                'field_label' => 'From Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Source branch is required.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'to_branch_id',
                'field_label' => 'To Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Destination branch is required.',
                'sort_order' => 3,
            ],

            // Opening Stocks
            [
                'module_key' => 'opening_stocks',
                'field_name' => 'entry_date',
                'field_label' => 'Opening Entry Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'opening_stocks',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'opening_stocks',
                'field_name' => 'remarks',
                'field_label' => 'Remarks',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],

            // Damage Stocks
            [
                'module_key' => 'damage_stocks',
                'field_name' => 'entry_date',
                'field_label' => 'Damage Entry Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'damage_stocks',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'damage_stocks',
                'field_name' => 'remarks',
                'field_label' => 'Remarks / Damage Reason',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],

            // Stock Updates
            [
                'module_key' => 'stock_updates',
                'field_name' => 'entry_date',
                'field_label' => 'Update Entry Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'stock_updates',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'stock_updates',
                'field_name' => 'remarks',
                'field_label' => 'Remarks / Reason',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],

            // ==========================================
            // 4. MASTER MODULES
            // ==========================================
            // Customers
            [
                'module_key' => 'customers',
                'field_name' => 'name',
                'field_label' => 'Customer Name',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Customer name is required.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'mobile',
                'field_label' => 'Mobile Number',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Mobile number must be unique and valid.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'email',
                'field_label' => 'Email Address',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please enter a valid email address.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'gst_no',
                'field_label' => 'GSTIN',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'GSTIN is invalid.',
                'sort_order' => 4,
            ],

            // Suppliers
            [
                'module_key' => 'suppliers',
                'field_name' => 'name',
                'field_label' => 'Supplier Name',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Supplier name is required.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'suppliers',
                'field_name' => 'mobile',
                'field_label' => 'Mobile Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please enter a valid mobile number.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'suppliers',
                'field_name' => 'gst_no',
                'field_label' => 'GSTIN',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'GSTIN is invalid.',
                'sort_order' => 3,
            ],

            // Item Master
            [
                'module_key' => 'items',
                'field_name' => 'item_code',
                'field_label' => 'Item Code / Barcode',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Item Code must be unique.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'name',
                'field_label' => 'Item Name / Description',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Item name is required.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'category_id',
                'field_label' => 'Category',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'uom_id',
                'field_label' => 'Unit of Measure (UOM)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'cost_price',
                'field_label' => 'Cost Price',
                'field_type' => 'number',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'sell_price',
                'field_label' => 'Sell Price',
                'field_type' => 'number',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 6,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'mrp',
                'field_label' => 'MRP',
                'field_type' => 'number',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 7,
            ],
            [
                'module_key' => 'items',
                'field_name' => 'hsn_code',
                'field_label' => 'HSN Code (8 Digits)',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'HSN Code must be exactly 8 digits.',
                'sort_order' => 8,
            ],

            // Branch Master
            [
                'module_key' => 'branches',
                'field_name' => 'code',
                'field_label' => 'Branch Code',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'sort_order' => 1,
            ],
            [
                'module_key' => 'branches',
                'field_name' => 'name',
                'field_label' => 'Branch Name',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'sort_order' => 2,
            ],
            [
                'module_key' => 'branches',
                'field_name' => 'phone',
                'field_label' => 'Phone / Mobile',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 3,
            ],
            [
                'module_key' => 'branches',
                'field_name' => 'email',
                'field_label' => 'Email',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 4,
            ],
            [
                'module_key' => 'branches',
                'field_name' => 'gst_no',
                'field_label' => 'GSTIN',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'sort_order' => 5,
            ],
        ];

        foreach ($fields as $fieldData) {
            FormFieldValidation::updateOrCreate(
                [
                    'module_key' => $fieldData['module_key'],
                    'field_name' => $fieldData['field_name'],
                ],
                $fieldData
            );
        }
    }
}
