<?php

namespace Database\Seeders;

use App\Models\FormFieldValidation;
use Illuminate\Database\Seeder;

class FormFieldValidationSeeder extends Seeder
{
    public function run(): void
    {
        $fields = [
            // --- Purchase Invoices ---
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'invoice_date',
                'field_label' => 'Invoice Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date is not allowed for Invoice Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_id',
                'field_label' => 'Supplier',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select a valid supplier.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Branch selection is required.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'grn_number',
                'field_label' => 'GRN Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => true,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'GRN Number already exists. Please use a unique GRN Number.',
                'sort_order' => 4,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'grn_date',
                'field_label' => 'GRN Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for GRN Date.',
                'sort_order' => 5,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_no',
                'field_label' => 'Supplier Inv No',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Supplier Invoice Number is already recorded for this supplier.',
                'sort_order' => 6,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_date',
                'field_label' => 'Supplier Inv Date',
                'field_type' => 'date',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => true,
                'custom_error_message' => 'Future date is not allowed for Supplier Inv Date.',
                'sort_order' => 7,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'supplier_inv_amount',
                'field_label' => 'Supplier Inv Amount',
                'field_type' => 'number',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Inv Amount (Supplier) and Final Amount must match.',
                'sort_order' => 8,
            ],
            [
                'module_key' => 'purchase_invoices',
                'field_name' => 'purchase_type',
                'field_label' => 'Purchase Type (Local/Interstate)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please choose Local or Interstate purchase type.',
                'sort_order' => 9,
            ],

            // --- Sales Bills ---
            [
                'module_key' => 'sales_bills',
                'field_name' => 'bill_number',
                'field_label' => 'Bill Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => true,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Bill Number already exists.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'bill_date',
                'field_label' => 'Bill Date & Time',
                'field_type' => 'datetime',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date and time is not allowed for Bill Date.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'customer_id',
                'field_label' => 'Customer',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select a customer for this bill.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'branch_id',
                'field_label' => 'Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Branch selection is required.',
                'sort_order' => 4,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'invoice_type',
                'field_label' => 'Invoice Type',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please select an invoice type.',
                'sort_order' => 5,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'delivery_type',
                'field_label' => 'Delivery Type',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Delivery type is required.',
                'sort_order' => 6,
            ],
            [
                'module_key' => 'sales_bills',
                'field_name' => 'sales_type',
                'field_label' => 'Sales Type (Local/Interstate)',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Sales type is required.',
                'sort_order' => 7,
            ],

            // --- Stock Transfers ---
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'transfer_date',
                'field_label' => 'Transfer Date',
                'field_type' => 'date',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => true,
                'is_unique' => false,
                'custom_error_message' => 'Future date is not allowed for Transfer Date.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'from_branch_id',
                'field_label' => 'From Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Source branch is required.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'stock_transfers',
                'field_name' => 'to_branch_id',
                'field_label' => 'To Branch',
                'field_type' => 'select',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Destination branch is required.',
                'sort_order' => 3,
            ],

            // --- Customers ---
            [
                'module_key' => 'customers',
                'field_name' => 'name',
                'field_label' => 'Customer Name',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Customer name is required.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'mobile',
                'field_label' => 'Mobile Number',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => true,
                'custom_error_message' => 'Mobile number must be unique and valid.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'email',
                'field_label' => 'Email Address',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please enter a valid email address.',
                'sort_order' => 3,
            ],
            [
                'module_key' => 'customers',
                'field_name' => 'gstin',
                'field_label' => 'GSTIN',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'GSTIN is invalid.',
                'sort_order' => 4,
            ],

            // --- Suppliers ---
            [
                'module_key' => 'suppliers',
                'field_name' => 'name',
                'field_label' => 'Supplier Name',
                'field_type' => 'text',
                'is_required' => true,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Supplier name is required.',
                'sort_order' => 1,
            ],
            [
                'module_key' => 'suppliers',
                'field_name' => 'mobile',
                'field_label' => 'Mobile Number',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'Please enter a valid mobile number.',
                'sort_order' => 2,
            ],
            [
                'module_key' => 'suppliers',
                'field_name' => 'gstin',
                'field_label' => 'GSTIN',
                'field_type' => 'text',
                'is_required' => false,
                'is_readonly' => false,
                'block_future_date' => false,
                'is_unique' => false,
                'custom_error_message' => 'GSTIN is invalid.',
                'sort_order' => 3,
            ],
        ];

        foreach ($fields as $fieldData) {
            FormFieldValidation::updateOrCreate(
                [
                    'module_key' => $fieldData['module_key'],
                    'field_name' => $fieldData['field_name'],
                ],
                $fieldData
            );
        }
    }
}
